# Build and publish package when pushed to master

name: Publish Snapshot

on:
  push:
    branches:
      - master

env:
  JAVA_VERSION_TO_USE: '11'
  JAVA_DISTRI_TO_USE: 'corretto'

jobs:
  publish:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK ${{ env.JAVA_VERSION_TO_USE }} (${{ env.JAVA_DISTRI_TO_USE }})
      uses: actions/setup-java@v3
      with:
        java-version: ${{ env.JAVA_VERSION_TO_USE }}
        distribution: ${{ env.JAVA_DISTRI_TO_USE }}
        cache: maven

    - name: Build with Maven
      run: mvn -B package

    - name: Publish to GitHub Packages
      run: mvn -Pgithub deploy
      env:
        GITHUB_TOKEN: ${{ github.token }}
