# Build and publish package when release is created.
# SNAPSHOT suffix will be removed.

name: Publish Release

on:
  workflow_dispatch: # enable manual trigger

env:
  JAVA_VERSION_TO_USE: '11'
  JAVA_DISTRI_TO_USE: 'corretto'
  DEPLOY_RETRY: 5

jobs:
  publish:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK ${{ env.JAVA_VERSION_TO_USE }} (${{ env.JAVA_DISTRI_TO_USE }})
      uses: actions/setup-java@v3
      with:
        java-version: ${{ env.JAVA_VERSION_TO_USE }}
        distribution: ${{ env.JAVA_DISTRI_TO_USE }}
        cache: maven

    - name: Configure Git User
      run: git config user.name "Release Management"

    - name: Release Packages
      run: mvn -B -U -T 1C -Pgithub -DretryFailedDeploymentCount=${{ env.DEPLOY_RETRY }} release:prepare release:perform
      env:
        GITHUB_TOKEN: ${{ github.token }}
