# Build and publish package when pushed to master

name: Publish Snapshot

on:
  push:
    branches:
      - master

jobs:
  publish:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'corretto'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Publish to GitHub Packages
      run: mvn -Pgithub deploy
      env:
        GITHUB_TOKEN: ${{ github.token }}
