# Build and publish package when release is created.
# SNAPSHOT suffix will be removed.

name: Publish Release

on:
  release:
    types: [created]

jobs:
  publish:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Publish to GitHub Packages
      run: |
        mvn versions:set -DremoveSnapshot
        mvn -Pgithub deploy
      env:
        GITHUB_TOKEN: ${{ github.token }}
